### ISSUE TITLE
Enhancement: Open article within VSCode

### ISSUE THREAD

**Issue by akeeton** [ekarbe/rss-reader#3]
My biggest use case is to read articles within VSCode, rather than being taken to my browser.

I don't know much about RSS, but from two of the feeds I read using Outlook 2016, there is an embedded `content:encoded` tag containing HTML.  A full-blown embedded webview is probably impractical (and something I wouldn't want), but handling a subset of the textual elements could be reasonable.

Great project so far!

**Comment by ekarbe** [comment]
Thanks for the suggestion!

Could you provide me the RSS feeds with the tag please. Usually the feed entries just contain a more detailed description and not the full article.

Did you really mean to open/read the full article, or just the description?

**Comment by akeeton** [comment]
I have two snapshots of feeds that should be useful to compare.

The [normal Ars Technica feed][1] contains the first few paragraphs of articles and then links to read the remainder.  The ["pro" Ars Technica feed][2] contains complete articles.

> Did you really mean to open/read the full article, or just the description?

Yep! Throw these two feeds into [Feedly](https://feedly.com) and see for yourself.

  [1]: https://gist.github.com/akeeton/b0fd2a5728d93972da4d2e157aac9183
  [2]: https://gist.github.com/akeeton/07f4e30439c5c62dd1b7692090d66157

**Comment by ekarbe** [comment]
What do you think about adding the text to a terminal?

The content will be decoded to plain text and look like this:
```
Lorem ipsum. [//cdn.arstechnica.net/wp-content/uploads/2019/12/image.jpg]
Enlarge [//cdn.arstechnica.net/wp-content/uploads/2019/12/image.jpg] 
(credit: Image [https://www.image.com/])

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. 

At vero eos et accusam et justo duo dolores et ea rebum. 
Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. 
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt [https://www.lorem.com/ipsum] ut labore et dolore magna aliquyam erat, sed diam voluptua. 
At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

Read 4 remaining paragraphs [https://arstechnica.com/?p=ID1234] | Comments
[https://arstechnica.com/?p=ID1234&comments=1]

[http://feeds.feedburner.com/~ff/arstechnica/index?i=-KgwJa_Ur7o:-DHL5pwxA2w:V_sGLiPBpWU]
[http://feeds.arstechnica.com/~ff/arstechnica/index?a=-KgwJa_Ur7o:-DHL5pwxA2w:V_sGLiPBpWU] 
 
[http://feeds.feedburner.com/~ff/arstechnica/index?i=-KgwJa_Ur7o:-DHL5pwxA2w:F7zBnMyn0Lo]
[http://feeds.arstechnica.com/~ff/arstechnica/index?a=-KgwJa_Ur7o:-DHL5pwxA2w:F7zBnMyn0Lo] 
[http://feeds.feedburner.com/~ff/arstechnica/index?d=qj6IDK7rITs]
[http://feeds.arstechnica.com/~ff/arstechnica/index?a=-KgwJa_Ur7o:-DHL5pwxA2w:qj6IDK7rITs] 
[http://feeds.feedburner.com/~ff/arstechnica/index?d=yIl2AUoC8zA]
[http://feeds.arstechnica.com/~ff/arstechnica/index?a=-KgwJa_Ur7o:-DHL5pwxA2w:yIl2AUoC8zA]
```
I will probably split the feed links away as they are irrelevant.

**Comment by akeeton** [comment]
I was imagining the content would be shown in an editor window.

**Comment by ekarbe** [comment]
@akeeton I added the option to view the content/description of the articles in a preview editor.
