### ISSUE TITLE
Feature request: read\unread labels

### ISSUE THREAD

**Issue by v-iashin** [ekarbe/rss-reader#6]
It would be nice to have read/unread tags along with the lines. Can probably be achieved by changing the color of the links.

**Comment by ekarbe** [comment]
AFAIK there is no option to change the color of the TreeItems.
The option to hide or dispose of that item is not suited for this feature.

The only option I can think of is changing the color of the identifier, but that presumes the usage of an identifier for every source.

**Comment by ekarbe** [comment]
@v-iashin take a look at [vscode-rss](https://github.com/luyuhuang/vscode-rss) from @luyuhuang for this feature.
